### ISSUE TITLE
Warning: Each child in a list should have a unique "key" prop. found in Tab component

### ISSUE THREAD

**Issue by Ibabalola** [Capgemini/dcx-react-library#538] opened 2023-09-29 09:46 UTC
**Describe the bug**
Warning: Each child in a list should have a unique "key" prop.

Check the top-level render call using <div>. See https://reactjs.org/link/warning-keys for more information.
    at /.../node_modules/@capgeminiuk/dcx-react-library/dist/dcx-react-library.js:2039:3

**To Reproduce**
Render the <Tab /> compoent

**Expected behavior**
No warning

**Screenshots**

**Desktop (please complete the following information):**
- Chrome Version 117.0.5938.92
- Mac OS

**Comment by daniele-zurico** [comment] 2023-09-29 11:15
we have quite a lot of components available now in the library, can you please tell me which one is creating the problem to your side please?

**Comment by Ibabalola** [comment] 2023-09-29 17:38
TabGroup component

**Comment by alexwbbr** [comment] 2023-10-06 10:36
@daniele-zurico and @Ibabalola I have looked into this and found a solution. The part of tab group that is causing the problem is they key property on line 174 which is rendering the content of the currently active tab. Can the user ever see more than one tab content at the same time? If they can't then why is the active tab content being treated like an array when you can just render the one shown and remove the key property.

**Comment by alexwbbr** [comment] 2023-10-06 10:48
Never mind, saw the failing test for my solution and have another. Which branch should I use to make my pr? @daniele-zurico

**Comment by daniele-zurico** [comment] 2023-10-06 11:39
fixed by #540

**Closed by daniele-zurico** 2023-10-06 11:39 UTC
Labels: bug
